name: Create Release
description: Tags a repository and creates a GitHub Release.

outputs:
  version:
    description: New version number tagged in this release.
    value: ${{ steps.semver.outputs.version }}

runs:
  using: "composite"
  steps:
    - uses: paulhatch/semantic-version@v4.0.2
      id: semver
      name: Calculate version
      with:
        format: "${major}.${minor}.${patch}"
        short_tags: false
        tag_prefix: "v"

    - name: Add git tags
      env:
        MAJOR: ${{ steps.semver.outputs.major }}
        MINOR: ${{ steps.semver.outputs.minor }}
        VERSION: ${{ steps.semver.outputs.version }}
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        
        git tag --force -a -m "Add tag for release ${VERSION}" "v${VERSION}"
        git push --force origin "v${VERSION}"
        if [ "${MAJOR}" != "0" ]; then
          # optimistic tags move, so we force these operations
          git tag --force -a -m "Add major tag for release ${VERSION}" "v${MAJOR}"
          git push --force origin "v${MAJOR}"
          git tag --force -a -m "Add major.minor tag for release ${VERSION}" "v${MAJOR}.${MINOR}"
          git push --force origin "v${MAJOR}.${MINOR}"
        fi
      shell: bash
      
    - name: Generate changelog
      id: changelog
      uses: metcalfc/changelog-generator@v1.0.0
      with:
        myToken: ${{ github.token }}
 
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        body: ${{ steps.changelog.outputs.changelog }}
        tag_name: v${{ steps.semver.outputs.version }}
