name: Create Release
description: Tags a repository and creates a GitHub Release.

outputs:
  version:
    description: New version number tagged in this release.
    value: ${{ steps.semver.outputs.version }}

runs:
  using: "composite"
  steps:
    - uses: paulhatch/semantic-version@v4.0.2
      id: semver
      name: Calculate version
      with:
        tag_prefix: "v"
        format: "${major}.${minor}.${patch}"

    - name: Tag repository
      env:
        VERSION: ${{ steps.semver.outputs.version }}
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

        git tag --force -a -m "Add tag for release ${VERSION}" "v${VERSION}"
        git push --force origin "v${VERSION}"
      shell: bash
  
    - name: Generate changelog
      id: changelog
      uses: metcalfc/changelog-generator@v1.0.0
      with:
        myToken: ${{ github.token }}
 
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        body: ${{ steps.changelog.outputs.changelog }}
        tag_name: v${{ steps.semver.outputs.version }}
