name: Create Release
description: Tags a repository and creates a GitHub Release.

runs:
  using: "composite"
  steps:
    - uses: paulhatch/semantic-version@v4.0.2
      id: semver
      name: Calculate version
      with:
        tag_prefix: "v"
        format: "${major}.${minor}.${patch}"

    - name: Tag repository
      run: |
        git tag "v${{ steps.semver.outputs.version }}"
        git push origin "v${{ steps.semver.outputs.version }}"
      shell: bash
  
    - name: Generate changelog
      id: changelog
      uses: metcalfc/changelog-generator@v1.0.0
      with:
        myToken: ${{ github.token }}
 
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        body: ${{ steps.changelog.outputs.changelog }}
        tag_name: v${{ steps.semver.outputs.version }}
